import './Product.css'
import logo from '../assets/tastyburger logo.png'
import { useEffect, useState } from 'react'
import { allDayBreakfastProducts, chickenRiceMealProducts, dessertProducts, drinkProducts, flameGrilledProducts, fourCheeseWhopperProducts, getProductVariations, groupMealProducts, plantBasedWhopperProducts, products, tbCafeProducts, tbChickenBurgerProducts, tbSaversProducts, tbSpecialProducts, ultimateSideKicksProducts, whopperProducts, xtraLongChickenProducts } from './productData'
import type { BurgerVariation, Product } from './productData'

export function Rating({ value }: { value: number }) { return <span className="rating" aria-label={`${value} out of 5 stars`}>{[1, 2, 3, 4, 5].map((star) => <span key={star} className={star <= value ? 'star filled' : star - 0.5 === value ? 'star half' : 'star'}>★</span>)}</span> }
function BurgerAnimationLayer({ burgerName }: { burgerName: string }) { const animationClass = `anim-${burgerName.toLowerCase().replaceAll(' ', '-')}`; return <><div className={`steam-overlay ${animationClass}`} aria-hidden="true"><span className="steam steam-1" /><span className="steam steam-2" /><span className="steam steam-3" /></div><div className={`ingredient-overlay ${animationClass}`} /><div className="ingredient-particles"><div className="particle particle-1" /><div className="particle particle-2" /><div className="particle particle-3" /><div className="particle particle-4" /></div></> }
type ProductCardProps = { product: Product; isFavorite: boolean; onQuickView: (product: Product) => void; onToggleFavorite: (id: number) => void; onAddToCart: (product: Product) => void }
export function ProductCard({ product, isFavorite, onQuickView, onToggleFavorite, onAddToCart }: ProductCardProps) { return <article className={product.imageFit === 'contain' ? 'Product-card product-card-contained-image' : 'Product-card'}><div className="product-image-container"><img className="product-image" src={product.image} alt={product.name} /><BurgerAnimationLayer burgerName={product.name} /><button className="quick-view-overlay" onClick={() => onQuickView(product)} aria-label={`Quick view ${product.name}`}>VIEW BURGER</button></div><div className="card-content"><div className="rating-row"><Rating value={product.rating} /><button className={isFavorite ? 'favorite selected' : 'favorite'} onClick={() => onToggleFavorite(product.id)} aria-label={`${isFavorite ? 'Remove' : 'Add'} ${product.name} favorites`}>♡</button></div><h2>{product.name}</h2><p>{product.description}</p><button className="price-button" onClick={() => onAddToCart(product)} aria-label={`Add ${product.name} to cart`}>₱{product.price.toFixed(2)}</button></div></article> }
type ProductActionsProps = { favoriteIds: number[]; onQuickView: (product: Product) => void; onToggleFavorite: (id: number) => void; onAddToCart: (product: Product) => void }
type ProductGridProps = ProductActionsProps & { products: Product[] }
function ProductGrid({ products: productList, favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductGridProps) { return <div className="product-grid">{productList.map((product) => <ProductCard key={product.id} product={product} isFavorite={favoriteIds.includes(product.id)} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} />)}</div> }
export function Product({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="featured" aria-label="Burger menu"><ProductGrid products={products} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function GroupMeals({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="group-meals" className="group-meals-section" aria-labelledby="group-meals-title"><h2 id="group-meals-title">Group Meals</h2><ProductGrid products={groupMealProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function WhopperSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="whopper" className="whopper-section" aria-labelledby="whopper-title"><h2 id="whopper-title">Whopper</h2><ProductGrid products={whopperProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function FourCheeseWhopperSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="four-cheese-whopper" className="four-cheese-whopper-section" aria-labelledby="four-cheese-whopper-title"><h2 id="four-cheese-whopper-title">4-Cheese Whopper</h2><ProductGrid products={fourCheeseWhopperProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function XtraLongChickenSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="xtra-long-chicken" className="xtra-long-chicken-section" aria-labelledby="xtra-long-chicken-title"><h2 id="xtra-long-chicken-title">X-tra Long Chicken</h2><ProductGrid products={xtraLongChickenProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function TBChickenBurgerSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="tb-chicken-burger" className="tb-chicken-burger-section" aria-labelledby="tb-chicken-burger-title"><h2 id="tb-chicken-burger-title">TB Chicken Burger</h2><ProductGrid products={tbChickenBurgerProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function AllDayBreakfastSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="all-day-breakfast" className="all-day-breakfast-section" aria-labelledby="all-day-breakfast-title"><h2 id="all-day-breakfast-title">All-Day Breakfast</h2><ProductGrid products={allDayBreakfastProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function PlantBasedWhopperSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="plant-based-whopper" className="plant-based-whopper-section" aria-labelledby="plant-based-whopper-title"><h2 id="plant-based-whopper-title">Plant-Based Whopper</h2><ProductGrid products={plantBasedWhopperProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function FlameGrilledSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="flame-grilled" className="flame-grilled-section" aria-labelledby="flame-grilled-title"><h2 id="flame-grilled-title">Flame-Grilled Cheeseburger</h2><ProductGrid products={flameGrilledProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function TBSpecialSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="tb-special" className="tb-special-section" aria-labelledby="tb-special-title"><h2 id="tb-special-title">TB Special</h2><ProductGrid products={tbSpecialProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function ChickenRiceMealsSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="chicken-rice-meals" className="chicken-rice-meals-section" aria-labelledby="chicken-rice-meals-title"><h2 id="chicken-rice-meals-title">Chicken Rice Meals</h2><ProductGrid products={chickenRiceMealProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function UltimateSideKicksSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="ultimate-side-kicks" className="ultimate-side-kicks-section" aria-labelledby="ultimate-side-kicks-title"><h2 id="ultimate-side-kicks-title">Ultimate Side Kicks</h2><ProductGrid products={ultimateSideKicksProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function TBCafeSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="tb-cafe" className="tb-cafe-section" aria-labelledby="tb-cafe-title"><h2 id="tb-cafe-title">TB Cafe</h2><ProductGrid products={tbCafeProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function DrinksSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="drinks" className="drinks-section" aria-labelledby="drinks-title"><h2 id="drinks-title">Drinks</h2><ProductGrid products={drinkProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function DessertsSection({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="desserts" className="desserts-section" aria-labelledby="desserts-title"><h2 id="desserts-title">Desserts</h2><ProductGrid products={dessertProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }
export function TBSaversBundles({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: ProductActionsProps) { return <section id="tb-savers" className="tb-savers-section" aria-labelledby="tb-savers-title"><h2 id="tb-savers-title">TB Savers Bundles</h2><ProductGrid products={tbSaversProducts} favoriteIds={favoriteIds} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} /></section> }

export function BurgerVariationModal({ product, isOpen, onClose, onAddToCart }: { product: Product | null; isOpen: boolean; onClose: () => void; onAddToCart: (product: Product, variation: BurgerVariation, quantity: number) => void }) {
  const [selectedVariationId, setSelectedVariationId] = useState<BurgerVariation['id']>('regular')
  const [quantity, setQuantity] = useState(1)
  const variations = product ? getProductVariations(product) : []
  const selectedVariation = variations.find((variation) => variation.id === selectedVariationId) ?? variations[0]
  useEffect(() => { const handleEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; if (isOpen) { document.addEventListener('keydown', handleEscape); document.body.style.overflow = 'hidden' }; return () => { document.removeEventListener('keydown', handleEscape); document.body.style.overflow = '' } }, [isOpen, onClose])
  if (!isOpen || !product || !selectedVariation) return null
  return <div className="modal-backdrop" onClick={(event) => { if (event.target === event.currentTarget) onClose() }}><div className="variation-modal" role="dialog" aria-modal="true" aria-labelledby="variation-modal-title"><div className="variation-header"><img src={logo} alt="Tasty Burger" /><button className="modal-close" onClick={onClose} aria-label="Close modal">X</button><h2 id="variation-modal-title">Select Your Meal</h2></div><div className="variation-main-image"><img src={selectedVariation.image} alt={`${product.name} - ${selectedVariation.name}`} /></div><div className="variation-list">{variations.map((variation) => <button key={variation.id} className={variation.id === selectedVariationId ? 'variation-option selected' : 'variation-option'} onClick={() => setSelectedVariationId(variation.id)} aria-pressed={variation.id === selectedVariationId}><span className="variation-copy"><strong>{variation.name}</strong><span>{variation.description}</span><b>₱{variation.price.toFixed(2)}</b></span><img src={variation.image} alt="" /></button>)}</div><div className="variation-footer"><div className="quantity-selector"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Decrease quantity">-</button><span>{quantity}</span><button onClick={() => setQuantity(quantity + 1)} aria-label="Increase quantity">+</button></div><button className="add-to-cart-button" onClick={() => { onAddToCart(product, selectedVariation, quantity); onClose() }}>ADD TO CART <span>₱{(selectedVariation.price * quantity).toFixed(2)}</span></button></div></div></div>
}