import './Product.css'
import logo from '../assets/tastyburger logo.png'
import { useEffect, useState } from 'react'
import { getProductVariations, products } from './productData'
import type { BurgerVariation, Product } from './productData'

export function Rating({ value }: { value: number }) { return <span className="rating" aria-label={`${value} out of 5 stars`}>{[1, 2, 3, 4, 5].map((star) => <span key={star} className={star <= value ? 'star filled' : star - 0.5 === value ? 'star half' : 'star'}>★</span>)}</span> }
function BurgerAnimationLayer({ burgerName }: { burgerName: string }) { const animationClass = `anim-${burgerName.toLowerCase().replaceAll(' ', '-')}`; return <><div className={`steam-overlay ${animationClass}`} aria-hidden="true"><span className="steam steam-1" /><span className="steam steam-2" /><span className="steam steam-3" /></div><div className={`ingredient-overlay ${animationClass}`} /><div className="ingredient-particles"><div className="particle particle-1" /><div className="particle particle-2" /><div className="particle particle-3" /><div className="particle particle-4" /></div></> }
type ProductCardProps = { product: Product; isFavorite: boolean; onQuickView: (product: Product) => void; onToggleFavorite: (id: number) => void; onAddToCart: (product: Product) => void }
export function ProductCard({ product, isFavorite, onQuickView, onToggleFavorite, onAddToCart }: ProductCardProps) { return <article className="Product-card"><div className="product-image-container"><img className="product-image" src={product.image} alt={product.name} /><BurgerAnimationLayer burgerName={product.name} /><button className="quick-view-overlay" onClick={() => onQuickView(product)} aria-label={`Quick view ${product.name}`}>VIEW BURGER</button></div><div className="card-content"><div className="rating-row"><Rating value={product.rating} /><button className={isFavorite ? 'favorite selected' : 'favorite'} onClick={() => onToggleFavorite(product.id)} aria-label={`${isFavorite ? 'Remove' : 'Add'} ${product.name} favorites`}>♡</button></div><h2>{product.name}</h2><p>{product.description}</p><button className="price-button" onClick={() => onAddToCart(product)} aria-label={`Add ${product.name} to cart`}>₱{product.price.toFixed(2)}</button></div></article> }
export function Product({ favoriteIds, onQuickView, onToggleFavorite, onAddToCart }: { favoriteIds: number[]; onQuickView: (product: Product) => void; onToggleFavorite: (id: number) => void; onAddToCart: (product: Product) => void }) { return <section className="product-grid" aria-label="Burger menu">{products.map((product) => <ProductCard key={product.id} product={product} isFavorite={favoriteIds.includes(product.id)} onQuickView={onQuickView} onToggleFavorite={onToggleFavorite} onAddToCart={onAddToCart} />)}</section> }

export function BurgerVariationModal({ product, isOpen, onClose, onAddToCart }: { product: Product | null; isOpen: boolean; onClose: () => void; onAddToCart: (product: Product, variation: BurgerVariation, quantity: number) => void }) {
  const [selectedVariationId, setSelectedVariationId] = useState<BurgerVariation['id']>('regular')
  const [quantity, setQuantity] = useState(1)
  const variations = product ? getProductVariations(product) : []
  const selectedVariation = variations.find((variation) => variation.id === selectedVariationId) ?? variations[0]
  useEffect(() => { const handleEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; if (isOpen) { document.addEventListener('keydown', handleEscape); document.body.style.overflow = 'hidden' }; return () => { document.removeEventListener('keydown', handleEscape); document.body.style.overflow = '' } }, [isOpen, onClose])
  if (!isOpen || !product || !selectedVariation) return null
  return <div className="modal-backdrop" onClick={(event) => { if (event.target === event.currentTarget) onClose() }}><div className="variation-modal" role="dialog" aria-modal="true" aria-labelledby="variation-modal-title"><div className="variation-header"><img src={logo} alt="Tasty Burger" /><button className="modal-close" onClick={onClose} aria-label="Close modal">X</button><h2 id="variation-modal-title">Select Your Meal</h2></div><div className="variation-main-image"><img src={selectedVariation.image} alt={`${product.name} - ${selectedVariation.name}`} /></div><div className="variation-list">{variations.map((variation) => <button key={variation.id} className={variation.id === selectedVariationId ? 'variation-option selected' : 'variation-option'} onClick={() => setSelectedVariationId(variation.id)} aria-pressed={variation.id === selectedVariationId}><span className="variation-copy"><strong>{variation.name}</strong><span>{variation.description}</span><b>₱{variation.price.toFixed(2)}</b></span><img src={variation.image} alt="" /></button>)}</div><div className="variation-footer"><div className="quantity-selector"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Decrease quantity">-</button><span>{quantity}</span><button onClick={() => setQuantity(quantity + 1)} aria-label="Increase quantity">+</button></div><button className="add-to-cart-button" onClick={() => { onAddToCart(product, selectedVariation, quantity); onClose() }}>ADD TO CART <span>₱{(selectedVariation.price * quantity).toFixed(2)}</span></button></div></div></div>
}